# Grid World

grid_size: 5
grid_length: 100 # meters
agents:
 - {id: 0, wp: 13, charging_wp: 2 }
 - {id: 1, wp: 2 , charging_wp: 2 }
#  - {id: 3, wp: 21, charging_wp: 2 }
tasks:
  delivery:
    - {id: 0, pickup: 0, dropoff: 22}
    - {id: 1, pickup: 15, dropoff: 3}
    - {id: 2, pickup: 7, dropoff: 14}
    - {id: 3, pickup: 17, dropoff: 24}
    - {id: 4, pickup: 10, dropoff: 9}
    # - {id: 5, pickup: 4, dropoff: 8}
    # - {id: 6, pickup: 8, dropoff: 14}
    # - {id: 8, pickup: 5, dropoff: 11}
    # - {id: 9, pickup: 9, dropoff: 0}
    # - {id: 10, pickup: 1, dropoff: 3}
  
  station: [10,15,7,18,3,4,20,5,9,23] # not in used now


# 20--21--22--23--24
# |   |   |   |   |
# 15--16--17--18--19
# |   |   |   |   |
# 10--11--12--13--14
# |   |   |   |   |
# 05--06--07--08--09
# |   |   |   |   |
# 00--01--02--03--04
